apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: europe
  namespace: demo-europe
  labels:
    app: europe
spec:
  kafka:
    replicas: 1
    listeners:
      plain: {}
      tls: {}
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: true
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}