apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: my-topic
  namespace: demo-europe
  labels:
    strimzi.io/cluster: europe
spec:
  partitions: 3
  replicas: 1
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo-europe
  labels:
    app: kafka-producer
  name: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: kafka-producer
        image: quay.io/kafka-enablement-2020/kafka-producer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: europe-kafka-bootstrap:9092
          - name: TOPIC
            value: my-topic
          - name: TIMER
            value: "1000"
          - name: MESSAGE
            value: "Hello from Europe"
          - name: NUMBER_OF_KEYS
            value: "3"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo-europe
  labels:
    app: kafka-consumer
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: quay.io/kafka-enablement-2020/kafka-consumer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: europe-kafka-bootstrap:9092
          - name: PATTERN
            value: ".*my-topic.*"
          - name: GROUP_ID
            value: my-group